### ISSUE TITLE
jitpack.io library is not available

### ISSUE THREAD

**Issue by passos** [consenlabs/token-core-android#1]
Looks like the build was failed.

`https://jitpack.io/com/github/consenlabs/token-core-android/v0.1/build.log`

I also tried build the library from local, it failed because gradle wrapper has problem.

`错误: 找不到或无法加载主类 org.gradle.wrapper.GradleWrapperMain`

**Comment by XuNeal** [comment]
We found that the jitpack show the wrong building result. the `5ac7aa1d1a` does not build succeed either. But we have found how to fix this problem, pls come back one hour later. thanks

**Comment by XuNeal** [comment]
@passos Hey, We have fix this problem, pls try again, thanks.

**Comment by passos** [comment]
thanks for the update.

**Comment by XuNeal** [comment]
It seems this issue has already solved, I will close this issue, you can reopen it when you have any problem
