### ISSUE TITLE
deriveBitcoinWallet 创建IMTKeystore 需要用V3MnemonicKeystore，否则报ILLEGAL_OPERATION

### ISSUE THREAD

**Issue by demongel** [consenlabs/token-core-android#10]
在Identity中创建deriveBitcoinWallet  用到
IMTKeystore keystore = HDMnemonicKeystore.create(walletMetadata, password, mnemonicCodes, path);
可以创建成功，但是调用export报错，抛出ILLEGAL_OPERATION。看了下代码需要
keystore instanceof V3Keystore || keystore instanceof V3MnemonicKeystore，
改成用V3MnemonicKeystore创建后不报错。

**Comment by Leney** [comment]
确定这样不会出现什么问题吗？有经过时间或者实际操作验证吗？

**Comment by XuNeal** [comment]
@demongel 助记词推导的钱包会派生无数钱包，只导出一个私钥是不完整的。BTC默认是不建议使用单私钥钱包。请以助记词为主

**Comment by XuNeal** [comment]
如果你没后续问题，我先关掉此issue了。

**Comment by houcc1012** [comment]
![Uploading image.png…]()

**Comment by houcc1012** [comment]
比特币交易签名报can_not_found_private_key ,请问下需要怎么设置吗

**Comment by ganshenml** [comment]
> @demongel 助记词推导的钱包会派生无数钱包，只导出一个私钥是不完整的。BTC默认是不建议使用单私钥钱包。请以助记词为主

那要导出私钥怎么办？
