### ISSUE TITLE
导出BTC钱包私钥报错，

### ISSUE THREAD

**Issue by Leney** [consenlabs/token-core-android#11]
因为在创建BTC钱包的时候是用的HDMnemonicKeystore
而在到处私钥的时候有做过滤：
 public String exportPrivateKey(String password) {
    if (keystore instanceof V3Keystore || keystore instanceof V3MnemonicKeystore) {
      byte[] decrypted = keystore.decryptCiphertext(password);
      if (keystore.getMetadata().getSource().equals(Metadata.FROM_WIF)) {
        return new String(decrypted);
      } else {
        return NumericUtil.bytesToHex(decrypted);
      }
    }
    throw new TokenException(Messages.ILLEGAL_OPERATION);
  }

也就是说 只要不是V3Keystore 或者 V3MnemonicKeystore 类型的都会抛TokenException

所以想问下，如何导出BTC钱包私钥？？？？？

**Comment by XuNeal** [comment]
Duplicate of #13
