### ISSUE TITLE
Where can i use to get utxo and transactions?

### ISSUE THREAD

**Issue by mivanzhang** [consenlabs/token-core-android#12]
Where can i use to get utxo and transactions?
The api in blockchain doesnot give me the correct utxo when i use segwit

**Comment by vae520283995** [comment]
这个可能要自己搞个区块浏览器了

**Comment by XuNeal** [comment]
You can use the API of Blockchain.com or insight. just like https://github.com/bitpay/insight-api#unspent-outputs

**Comment by mivanzhang** [comment]
不需要啦，我找到办法了，等着我来开源吧

**Comment by vae520283995** [comment]
@mivanzhang 是扫块自己存储吗
