### ISSUE TITLE
Why export PrivateKey of BITCOIN Error

### ISSUE THREAD

**Issue by Leney** [consenlabs/token-core-android#13]
because "HDMnemonicKeystore" to create BITCOIN 
but export PrivateKey have：

public String exportPrivateKey(String password) {
     if (keystore instanceof V3Keystore || keystore instanceof V3MnemonicKeystore) {
       byte[] decrypted = keystore.decryptCiphertext(password);
     if (keystore.getMetadata().getSource().equals(Metadata.FROM_WIF)) {
       return new String(decrypted);
     } else {
      return NumericUtil.bytesToHex(decrypted);
     }
  }
 throw new TokenException(Messages.ILLEGAL_OPERATION);
}

NO "HDMnemonicKeystore" and throw TokenException.

so how to export BITCION PrivateKey?

**Comment by XuNeal** [comment]
You can just export the mnemonic when  the BTC  wallet created by menmonic. 
You can import your BTC WIF(the PrivateKey) to create an BTC Wallet. This wallet is stored as V3Keystore, and you can export the PrivateKey now.

**Comment by Leney** [comment]
> You can just export the mnemonic when the BTC wallet created by menmonic.
> You can import your BTC WIF(the PrivateKey) to create an BTC Wallet. This wallet is stored as V3Keystore, and you can export the PrivateKey now.

现在如果是通过助记词创建的BTC钱包，我可以先得到助记词，然后再得到私钥！而且通过这个私钥是可以成功导入BTC钱包的；但当我们用之前BTC的私钥导入BTC钱包的时候，是用V3Keystore创建的，而这时候如果我们通过V3Keystore的导出私钥的方式，导出的BTC私钥就不对，望解答一下，谢谢！

**Comment by Leney** [comment]
> > You can just export the mnemonic when the BTC wallet created by menmonic.
> > You can import your BTC WIF(the PrivateKey) to create an BTC Wallet. This wallet is stored as V3Keystore, and you can export the PrivateKey now.
> 
> 现在如果是通过助记词创建的BTC钱包，我可以先得到助记词，然后再得到私钥！而且通过这个私钥是可以成功导入BTC钱包的；但当我们用之前BTC的私钥导入BTC钱包的时候，是用V3Keystore创建的，而这时候如果我们通过V3Keystore的导出私钥的方式，导出的BTC私钥就不对，望解答一下，谢谢！

也就是，现在我用BTC私钥导入钱包，然后去导出私钥，就不对，导入之前的BTC私钥  和 导入之后获取的私钥不是一样的

**Comment by zhen6939** [comment]
@Leney 请问能否提供测试用例（代码形式）？

**Comment by Leney** [comment]
> @Leney 请问能否提供测试用例（代码形式）？

ETH是正常的，就是BTC会出现这种情况！
私钥导入BTC，这里有有稍作改动，加了一个钱包类型，不知道是不是Metadata的值设置有问题：
    /**
     * 导入钱包(私钥)
     *
     * @param type
     * @param privateKey
     * @param name
     * @param password
     * @return
     */
    public static Wallet importWalletFromPrivateKey(WalletType type, String privateKey, String name, String password) {
        Metadata metadata = new Metadata();
        metadata.setName(name);
        metadata.setPasswordHint("");
        // 从私钥导入
        metadata.setSource(Metadata.FROM_PRIVATE);
        metadata.setNetwork(Network.MAINNET);
        metadata.setSegWit(Metadata.P2WPKH);
        switch (type) {
            case BITCOIN:
                metadata.setChainType(ChainType.BITCOIN);
                break;
            case ETHEREUM:
                metadata.setChainType(ChainType.ETHEREUM);
                break;
            case EOS:
                metadata.setChainType(ChainType.EOS);
                break;
        }
        return WalletManager.importWalletFromPrivateKey(metadata, privateKey, password, true);
    }

导出私钥就是已有的api：
    public String exportPrivateKey(String password) {
        if (keystore instanceof V3Keystore || keystore instanceof V3MnemonicKeystore) {
            byte[] decrypted = keystore.decryptCiphertext(password);
            if (keystore.getMetadata().getSource().equals(Metadata.FROM_WIF)) {
                return new String(decrypted);
            } else {
                return NumericUtil.bytesToHex(decrypted);
            }
        }
        throw new TokenException(Messages.ILLEGAL_OPERATION);
    }

**Comment by XuNeal** [comment]
@Leney 从你提交的代码来看没什么问题，能否详细描述一下你说的导入和导出不匹配的情形，私钥的导入和导出都是WIF格式吗？还是HEX格式。不匹配是否是因为network的原因？默认根据netowrk不同WIF的内容会有差异。
最好能提供一个详细的输入和输出的示例。

**Comment by Leney** [comment]
> @Leney 从你提交的代码来看没什么问题，能否详细描述一下你说的导入和导出不匹配的情形，私钥的导入和导出都是WIF格式吗？还是HEX格式。不匹配是否是因为network的原因？默认根据netowrk不同WIF的内容会有差异。
> 最好能提供一个详细的输入和输出的示例。

你好，已经解决，是因为导入钱包的时候source格式不对，不是WIF格式，感谢您的解答！！！
