### ISSUE TITLE
导入钱包时候空指针问题，是不是少了什么环节？

### ISSUE THREAD

**Issue by yezipeng** [consenlabs/token-core-android#15]
public static Identity getCurrentIdentity() {
        Class var0 = Identity.class;
        synchronized(Identity.class) {
            if (currentIdentity == null) {
                currentIdentity = tryLoadFromFile();
            }

            return currentIdentity;
        }
    }

这个返回null，因为

  try {
            File file = new File(WalletManager.getDefaultKeyDirectory(), "identity.json");
            ObjectMapper mapper = (new ObjectMapper()).configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            mapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);
            IdentityKeystore keystore = (IdentityKeystore)mapper.readValue(file, IdentityKeystore.class);
            return new Identity(keystore);
        } catch (IOException var3) {
            return null;
        }

这个文件不存在；

public static Wallet importWalletFromPrivateKey(Metadata metadata, String prvKeyHex, String password, boolean overwrite) {
        IMTKeystore keystore = V3Keystore.create(metadata, password, prvKeyHex);
        Wallet wallet = flushWallet(keystore, overwrite);
        Identity.getCurrentIdentity().addWallet(wallet);
        return wallet;
    }

然后

  Identity.getCurrentIdentity().addWallet(wallet);  这个就空指针了，怎么初始化这个 identity.json？ 

谢谢！！！

**Comment by XuNeal** [comment]
需要先调用crateIdentity Or recoverIdentity。你可以再看看ReadME

**Comment by yezipeng** [comment]
感谢您的回复！

 public static V3MnemonicKeystore create(Metadata metadata, String password, List<String> mnemonicCodes, String path) {
//这里的create被赋值为 “”，那么底层将自动生成id(uuid)，这样子初始化的时候没法去定义 "identity.json"，后面又依赖这个identity.json。是不是我还遗漏了什么？谢谢您！
    return new V3MnemonicKeystore(metadata, password, mnemonicCodes, path, "");
  }


  private V3MnemonicKeystore(Metadata metadata, String password, List<String> mnemonicCodes, String path, String id) {

}

**Comment by yezipeng** [comment]
感谢您的贡献和回复！

**Comment by yezipeng** [comment]
新建钱包，调用crateIdentity Or recoverIdentity，由于 return new V3MnemonicKeystore(metadata, password, mnemonicCodes, path, "");， 最后一个参数id被赋值为“”，所以钱包id自动生成即uuid。后面导入其他钱包时候依赖identity.json，所以报错。不知道逻辑哪里不对了····
