### ISSUE TITLE
关于 Keystore 的加密与存储

### ISSUE THREAD

**Issue by ssyijiu** [consenlabs/token-core-android#16]
在 imTome 公众号看到这样的描述：
加密后的 Keystore(私钥存储文件) 存储在沙盒文件系统。只有私钥签名的场景下 Keystore 才会配合密码的输入解开得到对应私钥。

请问：

1、我在电脑上跑了下测试方法，发现 Keystore 的 json 文件是明文存储，并没有加密，是需要调用某个加密方法吗？

2、Keystore 的存储位置不是通过 KeystoreStorage 这个接口设置的吗？沙盒文件系统 是什么意思？指的是的 Android 的私有目录吗？

**Comment by vae520283995** [comment]
顺便问个，密码和种子是怎么对应加密存储的，怎么通过密码获取种子

**Comment by ssyijiu** [comment]
@vae520283995 密码 + Keystore = 私钥 = 种子，知道其中任何一个，都可以计算出其他两个

**Comment by XuNeal** [comment]
1. Keystore结构是明文存储的。但是私钥信息和助记词都是经过KDF加密存储的。KDF简单的理解就是将你输入的密码进行散列加密再散列再加密，运行到一定次数之后获取到的值才是真正用来加密的Key。更多的KDF信息你可以参见https://en.wikipedia.org/wiki/Key_derivation_function
2. 沙盒即Android的私有目录，提供了KeystoreStorage抽象接口是为了在单元测试中做Mock的，让单元测试可以在PC机上跑
3. 助记词可以通过exportMnemonic导出，然后使用接口生成助记词的seed，不过一般用户只会接触到助记词，不会接触到seed

**Comment by vae520283995** [comment]
@XuNeal 大神你好，请问，我在签名的时候输入的密码，然后就能签名，这中间是通过密码去找到对应的种子根据地址的索引签名的，但是我的密码和助记词是怎么存储的呢？请回答下，谢谢

**Comment by ssyijiu** [comment]
@XuNeal 多谢。
