### ISSUE TITLE
请问我需要直接获取BTC的私钥，有什么方法可以直接获取吗？

### ISSUE THREAD

**Issue by lcaifu** [consenlabs/token-core-android#19]

**Comment by XuNeal** [comment]
目前在imToken创建的钱包都是HD钱包。是根据一个助记词按照不同的路径推演的。通过助记词可以获得所有私钥的控制权。具体详情参见http://book.8btc.com/books/6/masterbitcoin2cn/_book/ch05.html 确定性钱包一节

如果您是使用WIF(BTC 私钥的编码方式）导入的则可以直接导出私钥

**Comment by XuNeal** [comment]
该问题已经很久没回复了，我先关掉了
