### ISSUE TITLE
怎么获取钱包的余额呀？

### ISSUE THREAD

**Issue by zzsure** [consenlabs/token-core-android#21]
什么接口可以获取钱包，比如说BTC钱包，余额数量是多少该调用哪个函数？

**Comment by XuNeal** [comment]
可以通过BTC 可以blockchain api 或者insight api来查看余额，例如/insight-api/addr/[:addr]/balance
Ether可以直接通过etherscan等接口

**Comment by zzsure** [comment]
> 可以通过BTC 可以blockchain api 或者insight api来查看余额，例如/insight-api/addr/[:addr]/balance
> Ether可以直接通过etherscan等接口

为什么你们的这个sdk里面没有获取余额的接口呀？

**Comment by XuNeal** [comment]
当前这个只是一个SDK部分，主要考虑钱包管理的核心功能。至于第三方功能你可以随意接自己的服务或者已有的insight或者blockchain。不提供这些默认内置服务器也是考虑到钱包本身是个非常隐私的东西，token-core可以保证自己没有偷偷传输任何数据

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

**Comment by Aimeelu668** [comment]
谢谢楼楼精彩分享，我再补充一点，对于交易所这种业务型系统，选择钱包的时候需要考虑的问题，应该是安全的同时也需要快速的业务对接。相关业务上的难点有：安全、跨链整合、庞大的数据量、还有其他的业务需求比如生成地址、地址管理、资金管理、交易记录管理、充提币及回调等等。以优盾钱包——全球首款区块链交易所钱包对接开放平台为例，以上的难点都得到了解决，且业务上有主流语言的SDK可实现快速的对接： ①Java版 https://github.com/uduncloud/udun-sdk-java ②.Net版 https://github.com/uduncloud/udun-sdk-csharp ③Php版 https://github.com/uduncloud/udun-sdk-php 就安全而言，提供了Client-Gateway Solution（CGS）、Hareware-Gateway Solution（HGS）两套解决方案。
