### ISSUE TITLE
为什么创建的钱包地址ETH的不是以0X开头

### ISSUE THREAD

**Issue by ehunmayh** [consenlabs/token-core-android#23]

**Comment by vae520283995** [comment]
我是自己拼接了0x

**Comment by XuNeal** [comment]
嗯，这部分为了处理方便所有进来的数据都是非0x开头的，可以按照自行需要处理。另外关于ETH地址可以参见https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md 相关信息

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
