### ISSUE TITLE
比特币交易签名问题

### ISSUE THREAD

**Issue by houcc1012** [consenlabs/token-core-android#25]
UTXO类中 derivedPath 是怎么 传的

**Comment by ganshenml** [comment]
同问，还有调用的api可能没有scriptPubKey这个，这些都从哪里取到？

**Comment by lvshtwl** [comment]
> 同问，还有调用的api可能没有scriptPubKey这个，这些都从哪里取到？

UTXO 签名的时候里面derivedPath 这个参数是传？

**Comment by XuNeal** [comment]
scriptPubKey的定义参见：http://book.8btc.com/books/6/masterbitcoin2cn/_book/ch07.html
值可以从公开的第三方服务查到，例如insight API https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/docs/api-documentation.md#get-wallet-utxos
derivedPath确实是个不太常见的值，在imToken中是用来判断用那一把私钥来解锁该UTXO及你要花的钱所在的钱包地址对应的私钥。这个在imToken是计算好的，如果咱们自己没有，可以修改这部分代码，从0/0一直试下去直到找到相对应的私钥。
我看看这部分代码能不能修改一下更通用一点

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

**Comment by lingbaeryi-strong** [comment]
> > 同问，还有调用的API可能没有scriptPubKey这个，这些都从哪里取到？
> 
> UTXO签名的时候里面derivedPath这个参数是传？

传的是什么？

**Comment by lingbaeryi-strong** [comment]
> scriptPubKey的定义参见：[http](http://book.8btc.com/books/6/masterbitcoin2cn/_book/ch07.html)：//book.8btc.com/books/6/masterbitcoin2cn/_book/ch07.html 
> 值可以从公开的第三方服务查到，例如insight API [https://github.com/bitpay/ bitcore / blob / master / packages / bitcore-node / docs / api-documentation.md #get-wallet-utxos](https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/docs/api-documentation.md#get-wallet-utxos)
> derivedPath确实是个不太常常的值，在imToken中是用来判断用那一把私来自解锁该UTXO及你要花的钱所在的钱包地址对应的私钥。这个在imToken是计算好的，如果咱们自己没有，可以修改这部分代码，从0/0一直试下去直到找到相对应的私钥。
> 我看看这部分代码能不能修改一下更通用一点

如何试？

**Comment by lingbaeryi-strong** [comment]
> This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

ios 的更新了  Android也能更新一下吗？
