### ISSUE TITLE
如何查询BTC钱包下所有得子地址

### ISSUE THREAD

**Issue by zq568680650** [consenlabs/token-core-android#26]

**Comment by XuNeal** [comment]
1. 创建BTC钱包之后会返回xpub。使用该XPub从blockchain.info的API中可以查到所有用过的UTXO和地址等
2. 使用接口Wallet接口中的newReceiveAddress地址可以推算出获取指定id的收款地址

**Comment by zq568680650** [comment]
请问交易时需要一个UTXO，UTXO里面得数据是从哪里获得呢，sdk里我看数据是写死得

**Comment by XuNeal** [comment]
blockchain.info也有查询utxo相关接口，你可以查找一下

**Comment by zq568680650** [comment]
谢谢您得回答，感谢您提供得这部分源码，通过集成imtoken我已经写好了btc钱包的功能，中间有些曲折得地方，建议可以适当多提供一些案例或者在方法上注明一些解释，方便开发者集成和开发，尤其是网络交互一块，此sdk并没有涉及，我觉得应该给开发者说明

**Comment by XuNeal** [comment]
十分抱歉，确实这部分还需要很多优化和提高，也欢迎各位fork和提PR
