### ISSUE TITLE
btc交易手续费的计算

### ISSUE THREAD

**Issue by whatisoop** [consenlabs/token-core-android#27]
构建BitcoinTransaction对象时，如何根据交易大小去计算手续费，项目中没有看到相关实现

**Comment by XuNeal** [comment]
因为交易网络堵塞是比较常见的事情，所以目前交易费是在服务器根据当前行情动态计算的。你可以参见https://www.buybitcoinworldwide.com/fee-calculator/

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

**Comment by kylodw** [comment]
你好，请教下，如果没有确定用户的输入utxo，怎么计算手续费？默认为2吗
