### ISSUE TITLE
Installation failed with message INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113

### ISSUE THREAD

**Issue by StarAndRainbow** [consenlabs/token-core-android#3]
你好，导入你的库之后，安装app提示：Installation failed with message INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113，
安装的手机cpu类型是armv7l，在build里面配置了
 splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'mips', 'mips64', 'arm64-v8a','arm'
            universalApk true
        }
    }

这个问题你知道是什么原因造成的吗

**Comment by StarAndRainbow** [comment]
> 刚刚测试了一下模拟器上会出现这个问题，我们调试一下，你能先用真机试试嘛？

我这边是在真机上遇到的，小米8se和华为的nova 2 Plus 都会出现这种情况

**Comment by qimingnan** [comment]
小米mix2s也有同样的问题
MIUI10.0.3.0稳定版，Android 8.0.0

**Comment by XuNeal** [comment]
@StarAndRainbow @qimingnan 麻烦参见一下步骤尝试一下具体的说明可以参见相关的引用

Step 4. (Optional) When you wants to debug your app in Android Oreo you shoud add the blow code to your build.gradle. Pls ref to https://issuetracker.google.com/issues/65941637 for more info.

android {
    ……
    packagingOptions {
        exclude 'lib/x86_64/darwin/libscrypt.dylib'
    }
   ……
}

**Comment by StarAndRainbow** [comment]
感谢你的回复，我配置之后，该问题依旧存在，提示Failed to extract native libraries, res=-113之后，我点击ok提示
Unknown failure (at android.os.Binder.execTransact(Binder.java:675))
Error while Installing APK
对于上面的问题，参考下面的链接，解决不了了我的问题
https://stackoverflow.com/questions/42781934/android-error-while-installing-apks

**Comment by StarAndRainbow** [comment]
如果我直接打成debug的apk，放置到华为手机上，安装的时候会提示：安装事变，该应用与此设备的CPU不兼容

**Comment by StarAndRainbow** [comment]
如果我直接打成debug的apk，放置到华为手机上，安装的时候会提示：安装失败，该应用与此设备的CPU不兼容

**Comment by XuNeal** [comment]
请问这个配置项你是放在你的APP内的build.gradle中，不是token-core-android中。另外请问你试过低于Android8.0的版本吗？

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
