### ISSUE TITLE
Metadata().getName()获取的名称始终为btc

### ISSUE THREAD

**Issue by ganshenml** [consenlabs/token-core-android#30]
创建的时候是通过这种方式创建btc钱包的：
public static Wallet createWallet(String name, String passphrase, String passHint) {
        LogUtil.e(TAG, "createWallet——>name:" + name + " passphrase:" + passphrase + " passHint:" + passHint);
        Identity identity = Identity.createIdentity(name, passphrase, passHint, NET_STRING, Metadata.P2WPKH);//默认隔离见证
        Wallet mWallet = identity.getWallets().get(1);
        showWalletInfoLog(mWallet, passphrase);
        LogUtil.e(TAG, "createWallet——>walletName:" + mWallet.getMetadata().getName());
        WalletManager.scanWallets();
        return mWallet;
    }
    }

之后通过wallet.getMetadata().getName();则输出的是：“**BTC**”

**Comment by XuNeal** [comment]
目前由identity推导的钱包默认名称都是BTC或者ETH。在imToken的官方App中所有显示名称都是在前端维护的，只要保证正常操作时调用的API中传入的WalletID和TokenCore是一一对应即可，你也可以参考这种设计方案。或者直接fork源代码修改成适宜的派生命名方案

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
