### ISSUE TITLE
异常：ScriptException("Push of data element that is larger than remaining data")

### ISSUE THREAD

**Issue by diaoyutian** [consenlabs/token-core-android#31]
public void sign() {
        String pin = mEt_pin.getText().toString();
        String toAddress = mEt_transalate_address.getText().toString().trim();
        ArrayList<BitcoinTransaction.UTXO> list = new ArrayList<>();
        String network = mWallet.getMetadata().getNetwork();
        String privateKey = mWallet.exportPrivateKey(pin);
        ECKey ecKey = ECKey.fromPrivate(privateKey.getBytes());
        String publicKeyAsHex = ecKey.getPublicKeyAsHex();

        list.add(new BitcoinTransaction.UTXO(
                "d6e98b7a582a1b95e273e7ac903bde5c87bf7836cc73a13114d06383e71dd68a",
                0,
                9110000,
                mWallet.getAddress(),
                publicKeyAsHex,
                "0/0"
        ));

        BitcoinTransaction transaction = new BitcoinTransaction(toAddress, 0, 100000, 100,
                list);

        String chainId = Network.MAINNET.equals(network) ? ChainId.BITCOIN_MAINNET + ""
                : ChainId.BITCOIN_TESTNET + "";
        TxSignResult txSignResult = transaction.signTransaction(chainId, pin, mWallet);
        String signedTx = txSignResult.getSignedTx();
        String txHash = txSignResult.getTxHash();
        Log.d("sendBTC", "signedTx = " + signedTx);
        Log.d("sendBTC", "txHash = " + txHash);
    }

UTXO的scriptPubKey参数是我的公钥吗？derivedPath是自己指定吗？

**Comment by XuNeal** [comment]
derivedPath不是自己指定的，是指你要用HD路径上那个私钥解锁这个签名。
scriptPubKey如果不是segWit钱包地话基本是一个固定值，你可以看看insight提供的API。另外scriptPubKey的定义可以参见：http://book.8btc.com/books/6/masterbitcoin2cn/_book/ch07.html

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

**Comment by lingbaeryi-strong** [comment]
> 指你要用HD路径上那个私钥解锁这个  那应该传什么？ 怎么获取 或者转换
