### ISSUE TITLE
Attempt to invoke virtual method 'void org.consenlabs.tokencore.wallet.Identity.addWallet(org.consenlabs.tokencore.wallet.Wallet)' on a null object reference

### ISSUE THREAD

**Issue by ganshenml** [consenlabs/token-core-android#32]
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.consenlabs.tokencore.wallet.Identity.addWallet(org.consenlabs.tokencore.wallet.Wallet)' on a null object reference at org.consenlabs.tokencore.wallet.WalletManager.persistWallet(WalletManager.java:303)
at org.consenlabs.tokencore.wallet.WalletManager.importWalletFromMnemonic(WalletManager.java:191)
at org.consenlabs.tokencore.wallet.WalletManager.importWalletFromMnemonic(WalletManager.java:195)

**Comment by XuNeal** [comment]
该错误是在直接调用addWallet了吗？建议你是用WalletManager提供的公开API进行钱包的管理操作

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

**Comment by vinodpanzer** [comment]
But I got this error when importing a wallet using pvt key

**Comment by vinodpanzer** [comment]
But I got this error when importing a wallet using pvt key
