### ISSUE TITLE
如何获取钱包下得交易列表

### ISSUE THREAD

**Issue by zq568680650** [consenlabs/token-core-android#33]
在此sdk中未能看到获取当前钱包所有得交易列表，请问这里用得是哪个api

**Comment by ganshenml** [comment]
找公网的api.

**Comment by XuNeal** [comment]
BTC可以参见insight 提供的API。ETH可以参见infura.io

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
