### ISSUE TITLE
多链钱包的EOS钱包怎么创建

### ISSUE THREAD

**Issue by lvshtwl** [consenlabs/token-core-android#34]

**Comment by XuNeal** [comment]
默认创建identity的时候只会 推导Ethereum和Bitcoin钱包，如果想添加EOS的钱包可以通过`Identity.currentIdentity.deriveWallets(Collection.singleList("EOS"), password)` 来添加，参见https://github.com/consenlabs/token-core-android/blob/master/app/src/main/java/org/consenlabs/tokencore/wallet/Identity.java#L155

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
