### ISSUE TITLE
导出私钥报错：illegal_operation

### ISSUE THREAD

**Issue by ganshenml** [consenlabs/token-core-android#35]
之前的问题已经看过了。我这边创建钱包的方法有两个：
1.     Identity identity = Identity.createIdentity(name, passphrase, passHint, NET_STRING, Metadata.P2WPKH);//默认隔离见证

2.     Metadata metadata = new Metadata(ChainType.BITCOIN, NET_STRING, name, passHint, segWit);
       metadata.setSource(Metadata.FROM_MNEMONIC);
       Wallet mWallet = WalletManager.importWalletFromMnemonic(metadata, seedCode, BIP44Util.getBTCMnemonicPath(segWit, isMainNet), passphrase, true);

下面这个是通过助记词导入的。

在导出的时候调用方法：
WalletManager.exportPrivateKey(getWalletId(),getPassphrase());
就会报错，illegal_operation。但是导出助记词的方法是正常的。

请问这是什么原因？

**Comment by wbm0701** [comment]
我遇到了同样的问题，debug看了一下
public String exportPrivateKey(String password) {
    if (keystore instanceof V3Keystore || keystore instanceof V3MnemonicKeystore) {
      byte[] decrypted = keystore.decryptCiphertext(password);
      if (keystore.getMetadata().getSource().equals(Metadata.FROM_WIF)) {
        return new String(decrypted);
      } else {
        return NumericUtil.bytesToHex(decrypted);
      }
    }
    throw new TokenException(Messages.ILLEGAL_OPERATION);
  }

keysotore经过这里就报错了，因为检测出来不是这两个的实例欸，你解决了吗，我也不知道咋办

**Comment by ganshenml** [comment]
> 我遇到了同样的问题，debug看了一下
> public String exportPrivateKey(String password) {
> if (keystore instanceof V3Keystore || keystore instanceof V3MnemonicKeystore) {
> byte[] decrypted = keystore.decryptCiphertext(password);
> if (keystore.getMetadata().getSource().equals(Metadata.FROM_WIF)) {
> return new String(decrypted);
> } else {
> return NumericUtil.bytesToHex(decrypted);
> }
> }
> throw new TokenException(Messages.ILLEGAL_OPERATION);
> }
> 
> keysotore经过这里就报错了，因为检测出来不是这两个的实例欸，你解决了吗，我也不知道咋办

私钥导入的才支持导出私钥。

**Comment by XuNeal** [comment]
BTC的HD钱包是根据BIP44规则派生的。简单来说就是根据一个助记词派生无数个私钥，每个私钥会有对应的钱包地址，这么个做法可以显著提升匿名性。
所以如果你在HD的钱包导出一把私钥的话，那你其余的私钥的钱就不在你的控制下了。所以对于HD的钱包我们只支持导出助记词

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
