### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.consenlabs.tokencore.foundation.crypto.PBKDF2Params.getPrf()' on a null object reference

### ISSUE THREAD

**Issue by lvshtwl** [consenlabs/token-core-android#38]
deriveWallets 调用该方法报错

**Comment by XuNeal** [comment]
看起来应该是PBKDF2Params对象获取失败了，请问完整的复现流程是怎么样的呢？是否是在keystore序列化数据时失败了呢？

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
