### ISSUE TITLE
Code contain sample code

### ISSUE THREAD

**Issue by mivanzhang** [consenlabs/token-core-android#4]
[the code HDMnemonicKeystore](https://github.com/consenlabs/token-core-android/blob/master/app/src/main/java/org/consenlabs/tokencore/wallet/keystore/HDMnemonicKeystore.java) has a warning 
```java
// !!! Don't use this key in production !!!
  public static String XPubCommonKey128 = "B888D25EC8C12BD5043777B1AC49F872";
  public static String XPubCommonIv = "9C0C30889CBCC5E01AB5B2BB88715799";
```
so what can we use in product?

**Comment by XuNeal** [comment]
@mivanzhang We need the xpub to discovery other BTC address for collecting all utxos, and we collect that on the server-side. When we transfer the xpub from client to server, we encrypted it by AES. 
You can use the Random Number as the key and iv, just make sure is the same in server-side.

**Comment by mivanzhang** [comment]
so where is you server side code?

**Comment by XuNeal** [comment]
Sorry, There is much code about business in our backend, it's not a common library, so we are not going to make it opensource.

**Comment by mivanzhang** [comment]
Thank you ,but I cannot find api that can send my transaction in [blockchain](https://www.blockchain.com/api/blockchain_api), Can you give me a detailed url?

**Comment by XuNeal** [comment]
You can check the insight-api  https://github.com/bitpay/insight-api#transaction-broadcasting

**Comment by mivanzhang** [comment]
thank you very much
