### ISSUE TITLE
HDMnemonicKeystore这个类里面的两个参数的值是怎么生成的，为什么要明文显示

### ISSUE THREAD

**Issue by vae520283995** [consenlabs/token-core-android#40]
// !!! Don't use this key in production !!!
    public static String XPubCommonKey128 = "B888D25EC8C12BD5043777B1AC49F872";
    public static String XPubCommonIv = "9C0C30889CBCC5E01AB5B2BB88715799";

这两个值是用来加密助记词的，那么这个是怎么生成的？或者能不能用密码去生成这个，就不用每次都在代码里面明文写死了

**Comment by GalaxySciTech** [comment]
i have the  question same as  this

**Comment by chenhao597** [comment]
我也有同样的疑问 公司正在开发类似功能 不知道为什么 这个难道是个bug 需要官方的解答 不然 bug在心中 怎么过日子???

**Comment by hurunboy** [comment]
How should I solve this problem?

**Comment by dechaow** [comment]
这个是使用aes加密的key和iv，自己按照aes加密规则创建自己的key和iv就行。

**Comment by XuNeal** [comment]
这两个值不是用来加密助记词的，是用来加密XPub的。XPub是用来查找你相关的HD钱包地所有派生地址的。由于HD钱包地特殊性，你的所有钱都是分散在不同的地址上的，为了查找出你的总额，就需要找到你所有用过的地址。
原则上来说XPub是可以公开的，但是公开之后我也可以查到到你所有的钱包地址了，HD的匿名性也就形同虚设了。所以我们将XPub放在服务器上是经过了加密的。所以才会要求在你自己使用时替换只有你们自己知道的key和iv.
你可以使用TokenCore中提供的如下代码生成一个随机的hex串
`NumericUtil.bytesToHex(NumericUtil.generateRandomBytes(16))`

**Comment by vae520283995** [comment]
@XuNeal 明白了，谢谢
