### ISSUE TITLE
创建身份后  怎么更新钱包名和修改用户名

### ISSUE THREAD

**Issue by uchengwang** [consenlabs/token-core-android#41]

**Comment by XuNeal** [comment]
钱包名称可以直接更改相关的meta，用户名是指eos吗？
钱包名称这些信息是不会上链的。并且你也可以看到API中只需要使用walletID作为唯一标识，所以你再自己的App中可以有自己的命名管理系统，只要保证walletID和TokenCore生成的一致就可以了。

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
