### ISSUE TITLE
有包括转账功能的源码吗

### ISSUE THREAD

**Issue by lvshtwl** [consenlabs/token-core-android#42]

**Comment by XuNeal** [comment]
TokenCore主要包括钱包管理和签名相关操作，其他操作你完全可以直接和区块链节点交互。如果简单点你也可以使用相关的区块链浏览器提供的接口，比如BTC使用insight，ETH可以使用infura.io

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

**Comment by purplieee** [comment]
之前用过优盾钱包，感觉比较安全，我看他们家的优盾学院提供区块链相关的源码下载，可以试试。

**Comment by parcool** [comment]
我也问一下，ETH我知道了，但是BTC还是得自己搭建节点啊，至少目前看insight转到bitcore-node后需要自己搭建服务端啊。有没有公共的节点地址呢？

**Comment by Aimeelu668** [comment]
有呀 给你个地址https://gitee.com/cexchange/CoinExchange/tree/master/07_Uduncloud
