### ISSUE TITLE
UTXO(String txHash, int vout, long amount, String address, String scriptPubKey, String derivedPath)

### ISSUE THREAD

**Issue by lvshtwl** [consenlabs/token-core-android#44]
txHash scriptPubKey 这几个字段的数据从哪里来的

**Comment by XuNeal** [comment]
这些都可以在区块链节点上拿到。你可以通过区块链浏览器：https://www.blockchain.com/zh-cn/explorer，或者insight的API拿到相关信息 https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/docs/api-documentation.md

**Comment by lvshtwl** [comment]
感谢回复。目前公司项目用的token core 代码，快速开发了一个版本，后面会陆陆续续的请教

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
