### ISSUE TITLE
BitcoinTransaction btc转账的时候 地址有问题

### ISSUE THREAD

**Issue by lvshtwl** [consenlabs/token-core-android#45]
BitcoinTransaction 通过助记词导入的钱包在btc转账的时候，
  changeAddress = indexKey.toAddress(network);  这里的地址会变成其他的地址，导致转账的时候，钱包余额为0

**Comment by zq568680650** [comment]
btc钱包转正转账后会生成一个找零地址，钱包余额会存入到这个找零地址

**Comment by lvshtwl** [comment]
> btc钱包转正转账后会生成一个找零地址，钱包余额会存入到这个找零地址

我知道，但是这个找零地址是转账的地址的话。钱会存过去，我试了用私钥导入的btc钱包。找零地址是转账本身的那个地址，但是助记词导入的钱包，找零地址就是一个新的地址，导致转账一小笔钱，原来的钱包破产了

**Comment by zq568680650** [comment]
钱包是不会破产的，只是你的BTC会存到找零地址里去，BTC钱包交易只需要通过Xpub通过api接口获得该钱包的UTXO以及钱包余额，拿到UTXO就可以进行转账操作。实际上就是你知道你的私钥或助记词你就可以进行转账操作，只要你的钱包里有足够的btc

**Comment by lvshtwl** [comment]
> UTXO

UTXO 这个我知道。我说的imtoken，通过助记词导入的方式。找零地址会产生一个新的。导致转账的时候，钱会退不回去，因为找零地址是新的了
![image](https://user-images.githubusercontent.com/15059350/51106933-43fe2b80-1828-11e9-8726-979100938332.png)
zhe'l这里生成地址已经不是转账的那个钱包地址了，如果是私钥导入的没有这个问题，只有助记词会有，
我试了用imtoken的demo test  也有这个问题

**Comment by lvshtwl** [comment]
> 钱包是不会破产的，只是你的BTC会存到找零地址里去，BTC钱包交易只需要通过Xpub通过api接口获得该钱包的UTXO以及钱包余额，拿到UTXO就可以进行转账操作。实际上就是你知道你的私钥或助记词你就可以进行转账操作，只要你的钱包里有足够的btc

![image](https://user-images.githubusercontent.com/15059350/51107219-1b2a6600-1829-11e9-8a33-a055801aeaf7.png)
红圈那里就是找零地址，imtoken生成了一个新的地址，导致我转了很少的钱，剩余的钱返回不了原来的钱包，如果下面的地址是我转账的地址，。则不会有这个问题

**Comment by vae520283995** [comment]
@lvshtwl 你把找零的地址换成自己的地址就行了

**Comment by lvshtwl** [comment]
> @lvshtwl 你把找零的地址换成自己的地址就行了

所以说我是用imtoken的代码的 BitcoinTransaction 这个类，生成的hash值，
![image](https://user-images.githubusercontent.com/15059350/51107689-6f821580-182a-11e9-8477-125301989dd5.png)
在这一行代码会有问题，imtoken测试代码里面，用助记词方式能看出这个bug

**Comment by vae520283995** [comment]
@lvshtwl 这不是bug，这是比特币默认生成新的找零机制，如果你需要换成自己的地址，你把代码改下就行了，我这边遇到很多人需要改成自己的地址，就是改一个地方就行了

**Comment by lvshtwl** [comment]
> @lvshtwl 这不是bug，这是比特币默认生成新的找零机制，如果你需要换成自己的地址，你把代码改下就行了，我这边遇到很多人需要改成自己的地址，就是改一个地方就行了

能说一下改哪个地方吗？我现在只在上面的图中红圈改了，怕漏掉

**Comment by vae520283995** [comment]
@lvshtwl 加我qq520283995

**Comment by lvshtwl** [comment]
> @lvshtwl 加我qq520283995

申请了 1057774043我的号

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
