### ISSUE TITLE
Eos 能只能测试网吗

### ISSUE THREAD

**Issue by lvshtwl** [consenlabs/token-core-android#46]
![image](https://user-images.githubusercontent.com/15059350/51106999-858ed680-1828-11e9-8b86-710e353829d7.png)
关于eos 测试是这个吗

**Comment by XuNeal** [comment]
EOS 的测试网络只有Kylin 你可以参见这里https://www.cryptokylin.io/

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
