### ISSUE TITLE
如何获取一个btc钱包下面的所有余额？

### ISSUE THREAD

**Issue by ganshenml** [consenlabs/token-core-android#47]
说是获取UTXO，但是也得有地址，如何知道所有地址呢？分为找零地址和收款地址，找零地址哪里去获取呢？

**Comment by XuNeal** [comment]
最简单的获取余额的方案是直接使用blockchain.info这种API，将xpub作为参数传递过去，服务器会帮你遍历所有地址。imToken也是这么实现的 。
目前tokenCore内部并未实现API遍历所有找零地址，只提供了收款地址。你可以参照收款地址的实现代码，将bip path中的change部分从0修改为1即可。bip path的概念参见：https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

**Comment by wxq-wen** [comment]
测试网隔离见证的地址用xpub在blockchain上查询好像查询不到，不知道什么原因。
