### ISSUE TITLE
imtoken钱包iOS导出的keystore导入Android失败

### ISSUE THREAD

**Issue by ganshenml** [consenlabs/token-core-android#48]
会报错：private_key_address_not_match

@XuNeal

**Comment by XuNeal** [comment]
是通过Ethereum钱包导出再导入的吗？如果是的后麻烦确认一下两个导出接口导出的Address字段是否一直，是否是因为0x前缀的问题？

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
