### ISSUE TITLE
导入包后，编译正常，安装时报错。

### ISSUE THREAD

**Issue by zqbemail** [consenlabs/token-core-android#5]
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerFor_devDebug'

Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives

还有很多类似的

**Comment by StarAndRainbow** [comment]
你这个是因为方法抄错了65555..个方法，但是修正这个问题之后，你可能会遇到我遇到的这个问题

**Comment by nikan0925** [comment]
可能是方法数超了
https://developer.android.com/studio/build/multidex?hl=zh-cn

**Comment by XuNeal** [comment]
该问题已经很长时间没有回复了，我先关掉了，如果问题并未解决你可以重新打开
