### ISSUE TITLE
EOS 权限owner  active 这两个值是怎么来的

### ISSUE THREAD

**Issue by lvshtwl** [consenlabs/token-core-android#50]

**Comment by XuNeal** [comment]
EOS系统要求注册account的时候需要提供两把公钥分别绑定owner和active权限，这两个权限是每个账户默认必须存在的两个权限，创始账户只有一把公司钥，其实是owner和active都同时绑定的这一把公司钥

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
