### ISSUE TITLE
请教下你们ipfs地址和私钥是怎么产生的？

### ISSUE THREAD

**Issue by coderbradlee** [consenlabs/token-core-android#53]

**Comment by XuNeal** [comment]
私钥只要保证是Secp256K1椭圆曲线上的一个随机点就可以了。IPFS地址是是根据一个私钥进行MultiHash出来的详细算法参见:https://github.com/consenlabs/token-core-android/blob/master/app/src/main/java/org/consenlabs/tokencore/wallet/keystore/IdentityKeystore.java#L112

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
