### ISSUE TITLE
麻烦问一下 usdt 隔离签名怎么来？usdt 的普通签名正常

### ISSUE THREAD

**Issue by onesand** [consenlabs/token-core-android#54]

**Comment by vae520283995** [comment]
和btc的一模一样

**Comment by onesand** [comment]
是的，然后我弄了一个 usdt 的输出脚本，签名后广播发现 non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)

**Comment by vae520283995** [comment]
我是直接用的bitcoinj做的，没用imtoken的

**Comment by onesand** [comment]
能给隔离签名部分代码看看吗？

**Comment by vae520283995** [comment]
早回家过年了

**Comment by onesand** [comment]
好的，新年快乐哈。我再看看。

**Comment by vae520283995** [comment]
反正就是一个东西，你试试把那个fasle的地方改成true看看

**Comment by onesand** [comment]
嗯嗯谢谢，我去试试

**Comment by nimici1993** [comment]
你好 你的隔离签名问题解决了吗
