### ISSUE TITLE
EOS签名 EOSTransaction.ToSignObj对象的属性解释

### ISSUE THREAD

**Issue by Leney** [consenlabs/token-core-android#59]
EOS交易签名EOSTransaction.ToSignObj txHex属性值是组合好之后需要签名的json字符串转换成的16进制值吗？

**Comment by Leney** [comment]
现在我按照这样去签名，转账一直报3090003，而同样的参数用到ios那边，签名出来的字符串，是可以转账成功的

**Comment by XuNeal** [comment]
txHex确实是由eosjs序列化好的值，能否贴出相关的测试数据？

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
