### ISSUE TITLE
有没有相关资料讲解一下这个项目？

### ISSUE THREAD

**Issue by parcool** [consenlabs/token-core-android#66]
1.项目源码中全篇**0**注释；
2.README寥寥数字，甚至连EOS交易签名都没提到；

项目架构完全不了解的情况下很难看懂源码，甚至可以说连使用都不知道。有没有相关资料让学习一下啊？

**Comment by censhengde** [comment]
say 得well!

**Comment by FlyArthur** [comment]
同求

**Comment by XuNeal** [comment]
1. 考虑到注释维护不及时会变成一种bad smell，所以我们尽量使其代码可以自解释。不过在所有含有魔法数字的地方以及逻辑不清晰的地方我们都加入了注释说明。
2. EOS签名由于其实现过于灵活，我们使用了EOSJS作为部分实现 参见 https://github.com/consenlabs/token-core-android/issues/51
3. 很抱歉我们当时开发的过程中并未补充架构说明文档，这是我们当时疏忽了。不过如果想了解代码可以参见相关的单元测试目录，比如 里面的[TokenCoreTour.java](https://github.com/consenlabs/token-core-android/blob/master/app/src/test/java/org/consenlabs/tokencore/wallet/TokenCoreTour.java)

**Comment by XuNeal** [comment]
另外我们最近致力于开发了一套跨平台的TokenCore，使用Rust编写，希望可以提高代码质量和开发速度。有兴趣可以参考一下 [TokenCoreX](https://github.com/consenlabs/token-core)， 该项目包含了架构说明及更多文档，参见[TokenCoreX TECH](https://github.com/consenlabs/token-core/blob/dev/docs/TECH.zh.md)

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
