### ISSUE TITLE
交易状态监听方法没有加入

### ISSUE THREAD

**Issue by liupan163** [consenlabs/token-core-android#8]
会添加 监听链上交易状态变化的实现代码吗？  如以太坊上交易pending状态

**Comment by XuNeal** [comment]
这个库目前只负责签名和钱包管理，业务管理需要咱们额外处理了。
你也可以配合blockchain API 或者insight API使用

**Comment by XuNeal** [comment]
如果你没有后续问题我先关掉该issue了。如果你有后续问题可以随时打开
