### ISSUE TITLE
Application not defined in AndroidManifest.xml

### ISSUE THREAD

**Issue by Lynette-xin** [consenlabs/token-core-android#9]
把文件导入idea运行，在虚拟机上运行报错---Application not defined in AndroidManifest.xml，会是什么的原因？是这个配置文件没弄好吗

**Comment by XuNeal** [comment]
不太确定你说的运行是指？这是个library项目，不包含application项目。示例代码我们正在编写中

**Comment by zzsure** [comment]
@XuNeal 示例代码大约什么时候发布呀？

**Comment by XuNeal** [comment]
@zzsure 最近其他任务比较多，暂时没办法做出承诺，十分抱歉。

**Comment by XuNeal** [comment]
示例代码任务我们会放在相关的新任务中。这个task先关闭了哈。
